In [1]:
import numpy as np

In [4]:
# 2. Примеры создания массивов
list_data = [1, 2, 3, 4]
arr_from_list = np.array(list_data)
print(arr_from_list)

[1 2 3 4]


In [3]:
nested_list = [[1, 2], [3, 4]]
arr_2d = np.array(nested_list)
print(arr_2d)

[[1 2]
 [3 4]]


In [5]:
zeros_arr = np.zeros(5)
print(zeros_arr)

[0. 0. 0. 0. 0.]


In [6]:
ones_arr = np.ones((2, 3))
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
arange_arr = np.arange(0, 10, 2)
print(arange_arr)

[0 2 4 6 8]


In [8]:
print("Форма массива arr_2d:", arr_2d.shape)
print("Тип данных элементов:", arr_2d.dtype)

Форма массива arr_2d: (2, 2)
Тип данных элементов: int64


In [9]:
# Индексы и срезы
element = arr_2d[0, 1]
print("Элемент [0,1]:", element)

Элемент [0,1]: 2


In [10]:
subarray = arr_2d[:, 1]
print("Срез [:,1] (второй столбец):", subarray)

Срез [:,1] (второй столбец): [2 4]


In [11]:
slice = arange_arr[1:3]
print("Срез arange_arr[1:3]:", slice)

Срез arange_arr[1:3]: [2 4]


In [15]:
# Примеры векторных операций
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


In [14]:
sum_arr = a + b
print("Поэлементное сложение a + b:", sum_arr)

Поэлементное сложение a + b: [5 7 9]


In [16]:
prod_arr = a * b
print("Поэлементное умножение a * b:", prod_arr)

Поэлементное умножение a * b: [ 4 10 18]


In [17]:
mean_val = np.mean(a)
print("Среднее значение массива a:", mean_val)

Среднее значение массива a: 2.0


In [18]:
total_sum = np.sum(b)
print("Сумма элементов массива b:", total_sum)

Сумма элементов массива b: 15
